# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:bjOPZ+TJ3EEoYuZJmOUS95IfmOd6mGxEbjf6DFDx86nJooeoGy7db5DsL0MZByAukA5YzdJXCmqbztToqNgZYMFOLd/LPR5xLnvYF8TAE7SbWo764OHiUcu2LnNHbHKJ3ks0k16tdNhsCgyK4meHJ/alpd5k5UtIOBIrQ6aJpoXDtjQz125p5ZMYamB+/jb9nB+aJaQuCQTgTY/UeVwHgE2qGmMq82r8GwNLpLPW6JNdELvX,iv:+PDBmQpyZWPUZ5zkCyo11S+A2O5kL00UyPec31cBaQI=,tag:xGIufb7Zj1ft1+1NKK4Saw==,type:str]
sops:
  age:
    - recipient: age14w0qmf2mm775fcrup4ka6g78cpakyzq0n2f398a5qc95en5mksmsqyrggn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNFFuemJhTFZGUHpVSjBR
        VzlZNzl2MzlEYUNFYkZGM3U1R1VDM2w5dGwwCmFCa2NGbFpCSjZMWWNFSEFMNWRp
        N2pCeVJLeDRlbW5ibmVyNi9OMVFXRmcKLS0tIEN5WmpYU2ZuS1B0WnZBSVZtTVYw
        TUdkd2xiWmJpUFBFb2ptbjJSU1VnQ2MK3ZvR2hflvfpPRgv2tkV3hp3YJ0oIQ1vL
        oWFboNT+f20FthwYt9Ex+4H2tmhA8dn345KgVYA32w17lWbsjCCPAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-30T15:33:03Z"
  mac: ENC[AES256_GCM,data:QEiBMaEmsYuuKyWuAB575AyBKmGY8hXedQkfzn+NgH13wtObBWMP5Za3/YUpZ7S/tN9+Kh4caiyss8KFXH34220Z7uogZ+gP8Tjv2y2vq+tPlBub3exv0SzSUKWoJAItryqT5St/dU24zDT0ngsANhRHmaRF3j+Z25N7U1WE6j8=,iv:l1CZBSwmMUjd2SjWWHxjM0Dx/rAqJM+85Li/kPYrutk=,tag:r2CQqXN5rjrUXYF4U2wBgw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
