# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:HJkq+0lrAVmUDw1tq+PTe0Fqm72i58/2y9IcsDA7OCS6oPH+vfhXTA==,iv:HU+zTVCEvbfFsuMqDCo6OERKPUBlHUP8ALr0ak7FT0c=,tag:OxSTl20MDC5cvgjzeXrvnQ==,type:str]
sops:
  age:
    - recipient: age14w0qmf2mm775fcrup4ka6g78cpakyzq0n2f398a5qc95en5mksmsqyrggn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncEIwT21kWEhaMXZkWk9G
        U3M2a1pIMDV2SnU5YjloWW5taG9uOGt3TjNFClgzand0eFA3b1pVK1FHaXFuSUNi
        dVlkVTJaSmF2YmhzaHVWdldxalRmVE0KLS0tIEF0ajViOFRrNVUweitnV1lYRDkx
        elFLNEhCWGxtMWVRTmd2N2gxbzJoRUkKuKqi+tFwu/oPsGh7Q5VA8R5HVj6y8xLe
        02OWDSEAHK04rQyG5iIZhR6NSaTrRR/T+I2iwM8OiY3V8BWlC/AM0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-30T15:33:03Z"
  mac: ENC[AES256_GCM,data:BhMO4HYgYyP/fMPgKjSHk2j1UBhn1S5F0Ac8RVOzv4E5sLtDYTuw/KKDL248TMpDdMNBn1AmNxQk7bqFNybG9hXSA3DGCcqmLRrtnfkcC5zvkM6J4+3VK3AFrVhARuR93LY/HtdJFzFpL4cp8rnnOdFW+QuwFJr+b7k8oIZwqqc=,iv:dbL6jATr5rrazMyUjIr6wTsh8PV+X2oFkbvFEHbCKYU=,tag:r9brtL9t2TyzZ1hpzUDB+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
