# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.178.30:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.178.30"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "ks-01"
    ipAddress: "192.168.178.111"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:74:f4:55"
        dhcp: false
        addresses:
          - "192.168.178.111/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.178.1"
        mtu: 1500
        vip:
          ip: "192.168.178.30"
  - hostname: "ks-02"
    ipAddress: "192.168.178.112"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:41:e1:ac"
        dhcp: false
        addresses:
          - "192.168.178.112/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.178.1"
        mtu: 1500
        vip:
          ip: "192.168.178.30"
  - hostname: "ks-03"
    ipAddress: "192.168.178.113"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:f4:b1:c9"
        dhcp: false
        addresses:
          - "192.168.178.113/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.178.1"
        mtu: 1500
        vip:
          ip: "192.168.178.30"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

