apiVersion: v1
kind: Secret
metadata:
  name: volsync-password
  namespace: volsync-system
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:KBYoFaNo7Y5mzrg=,iv:Mpvm4tb8f9HszqC3u3lq3+CzkV0iZtMbcu70NRIImqY=,tag:q1LWFfeu0m6AXlU6bl3ljQ==,type:str]
sops:
  age:
    - recipient: age14w0qmf2mm775fcrup4ka6g78cpakyzq0n2f398a5qc95en5mksmsqyrggn
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Z1lSR1h5TVFJeUthOURP
        cXVJaUsrYU9VbW9SMDVoSWQrQ3RvejFhUkhNCk8zZzR2YnRSRUh0YjkxdHV2cDl6
        Zm5LcFFCcVdwekpWcXBFbUhkcWhnQmsKLS0tIDlhV2RrQ1RZaEZJN2l3bXJ2d3N3
        Y0JjY0JBaGgyM0ovTGtXdXQycWFldDQK5UB1SJetD7yryRDlcVabzX4gBnkTxHW0
        /h3XDJ1ZzS7Vs4v4YFOxaxfPRB0TCGv0rJGX985276uMpSy8E7czSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-30T21:43:48Z"
  mac: ENC[AES256_GCM,data:bIf+HNJLvIyoVJ4rX7UG+rhafHpMr+9rX6YscxlsD1eEyXF8QpeQaT5/JnauEt3ET6YzTztZnVYy/aXgS0PEqp7g2JpOsisp/KjjwZK1/k+DwYWMbNAmj/H4ZqQo8yiDY3O9cVS3lnzGh9hR7ugeaXbitRC+oAkRwAvlUs4H0+0=,iv:DZurk0qJWu/pND65SMh3bgN0h5VyC6LV11uv2MMCSMc=,tag:NJAu5bciqriRihvxg+Kbyg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
